# Generated by Django 4.0.4 on 2022-05-18 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Horas_Extra', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carga_Horaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Entrada', models.DateTimeField()),
                ('Saida', models.DateTimeField()),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargos', models.CharField(max_length=255)),
                ('Departamento', models.CharField(max_length=255)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.empresa')),
            ],
        ),
    ]
