# Generated by Django 4.0.4 on 2022-05-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nostas',
            new_name='Notas',
        ),
    ]
